### ISSUE TITLE
No need to use an external package for async 

### ISSUE THREAD

**Issue by EwanValentine** [markdouthwaite/ortho#1]
See here:
https://github.com/markdouthwaite/ortho/blob/6a1c27c96e5199f664bd9190b53c58291d657c2b/src/user.js#L21

You can achieve this will:
```
await Promise.all(users.map(({ username, password, admin }) =>
  createUser(username, password, admin, callback)));
```

You can also destructure the params you need, instead of using _. <- you don't see that convention used a lot in JS, although it will work fine. Normally when you see an underscore as a param, it means it's not being used

**Comment by markdouthwaite** [comment]
Ah cool, good to know! Thanks. Switched over!
